---
- name: Fetch OS, RAM, and CPU information
  hosts: all
  gather_facts: yes
 
  tasks:
    - name: Display OS information
      debug:
        msg: "Hostname: {{ ansible_hostname }}, OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
 
    - name: Display RAM information
      debug:
        msg: "Hostname: {{ ansible_hostname }}, RAM: {{ ansible_memtotal_mb }} MB"
 
    - name: Display CPU information
      debug:
        msg: "Hostname: {{ ansible_hostname }}, CPU Cores: {{ ansible_processor_cores }}, CPU Model: {{ ansible_processor }}"
